var annotated =
[
    [ "detail", null, [
      [ "param_traits", "structdetail_1_1param__traits.html", null ],
      [ "param_traits< T, std::enable_if_t< std::is_same< T, std::string >::value > >", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01scde0d525df0d96b6aec7f29ce55192dd.html", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01scde0d525df0d96b6aec7f29ce55192dd" ],
      [ "param_traits< T, std::enable_if_t< std::is_same< T, boost::string_view >::value > >", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01b0b4dc0bbfaacd87dff74027031713730.html", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01b0b4dc0bbfaacd87dff74027031713730" ],
      [ "param_traits< T, std::enable_if_t< std::is_same< T, oscpack::small_string >::value > >", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01o0f30768c646fbcda17e384a6b877cdd0.html", "structdetail_1_1param__traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__same_3_01_t_00_01o0f30768c646fbcda17e384a6b877cdd0" ]
    ] ],
    [ "eggs", null, [
      [ "variants", null, [
        [ "variant", "classeggs_1_1variants_1_1variant.html", null ]
      ] ]
    ] ],
    [ "KDNSSD", null, [
      [ "PublicService", "class_k_d_n_s_s_d_1_1_public_service.html", null ]
    ] ],
    [ "osc", null, [
      [ "listener", "classosc_1_1listener.html", "classosc_1_1listener" ],
      [ "receiver", "classosc_1_1receiver.html", "classosc_1_1receiver" ],
      [ "sender", "classosc_1_1sender.html", "classosc_1_1sender" ]
    ] ],
    [ "oscpack", null, [
      [ "detail", null, [
        [ "ClearListener", "structoscpack_1_1detail_1_1_clear_listener.html", "structoscpack_1_1detail_1_1_clear_listener" ],
        [ "ReceiveSocket", "classoscpack_1_1detail_1_1_receive_socket.html", "classoscpack_1_1detail_1_1_receive_socket" ]
      ] ],
      [ "MessageGenerator", "classoscpack_1_1_message_generator.html", "classoscpack_1_1_message_generator" ],
      [ "DynamicMessageGenerator", "classoscpack_1_1_dynamic_message_generator.html", "classoscpack_1_1_dynamic_message_generator" ]
    ] ],
    [ "ossia", null, [
      [ "comparisons", null, [
        [ "Impulse_T", "structossia_1_1comparisons_1_1_impulse___t.html", "structossia_1_1comparisons_1_1_impulse___t" ],
        [ "String_T", "structossia_1_1comparisons_1_1_string___t.html", "structossia_1_1comparisons_1_1_string___t" ],
        [ "NumericValue", "structossia_1_1comparisons_1_1_numeric_value.html", null ],
        [ "StringValue", "structossia_1_1comparisons_1_1_string_value.html", null ],
        [ "TupleVisitor", "structossia_1_1comparisons_1_1_tuple_visitor.html", "structossia_1_1comparisons_1_1_tuple_visitor" ],
        [ "TupleValue", "structossia_1_1comparisons_1_1_tuple_value.html", null ],
        [ "DestinationVisitor", "structossia_1_1comparisons_1_1_destination_visitor.html", "structossia_1_1comparisons_1_1_destination_visitor" ],
        [ "DestinationValue", "structossia_1_1comparisons_1_1_destination_value.html", null ],
        [ "VecVisitor", "structossia_1_1comparisons_1_1_vec_visitor.html", "structossia_1_1comparisons_1_1_vec_visitor" ],
        [ "VecValue", "structossia_1_1comparisons_1_1_vec_value.html", null ]
      ] ],
      [ "detail", "namespaceossia_1_1detail.html", "namespaceossia_1_1detail" ],
      [ "easing", null, [
        [ "ease", "structossia_1_1easing_1_1ease.html", "structossia_1_1easing_1_1ease" ],
        [ "linear", "structossia_1_1easing_1_1linear.html", "structossia_1_1easing_1_1linear" ],
        [ "quadraticIn", "structossia_1_1easing_1_1quadratic_in.html", "structossia_1_1easing_1_1quadratic_in" ],
        [ "quadraticOut", "structossia_1_1easing_1_1quadratic_out.html", "structossia_1_1easing_1_1quadratic_out" ],
        [ "quadraticInOut", "structossia_1_1easing_1_1quadratic_in_out.html", "structossia_1_1easing_1_1quadratic_in_out" ],
        [ "cubicIn", "structossia_1_1easing_1_1cubic_in.html", "structossia_1_1easing_1_1cubic_in" ],
        [ "cubicOut", "structossia_1_1easing_1_1cubic_out.html", "structossia_1_1easing_1_1cubic_out" ],
        [ "cubicInOut", "structossia_1_1easing_1_1cubic_in_out.html", "structossia_1_1easing_1_1cubic_in_out" ],
        [ "quarticIn", "structossia_1_1easing_1_1quartic_in.html", "structossia_1_1easing_1_1quartic_in" ],
        [ "quarticOut", "structossia_1_1easing_1_1quartic_out.html", "structossia_1_1easing_1_1quartic_out" ],
        [ "quarticInOut", "structossia_1_1easing_1_1quartic_in_out.html", "structossia_1_1easing_1_1quartic_in_out" ],
        [ "quinticIn", "structossia_1_1easing_1_1quintic_in.html", "structossia_1_1easing_1_1quintic_in" ],
        [ "quinticOut", "structossia_1_1easing_1_1quintic_out.html", "structossia_1_1easing_1_1quintic_out" ],
        [ "quinticInOut", "structossia_1_1easing_1_1quintic_in_out.html", "structossia_1_1easing_1_1quintic_in_out" ],
        [ "sineIn", "structossia_1_1easing_1_1sine_in.html", "structossia_1_1easing_1_1sine_in" ],
        [ "sineOut", "structossia_1_1easing_1_1sine_out.html", "structossia_1_1easing_1_1sine_out" ],
        [ "sineInOut", "structossia_1_1easing_1_1sine_in_out.html", "structossia_1_1easing_1_1sine_in_out" ],
        [ "circularIn", "structossia_1_1easing_1_1circular_in.html", "structossia_1_1easing_1_1circular_in" ],
        [ "circularOut", "structossia_1_1easing_1_1circular_out.html", "structossia_1_1easing_1_1circular_out" ],
        [ "circularInOut", "structossia_1_1easing_1_1circular_in_out.html", "structossia_1_1easing_1_1circular_in_out" ],
        [ "exponentialIn", "structossia_1_1easing_1_1exponential_in.html", "structossia_1_1easing_1_1exponential_in" ],
        [ "exponentialOut", "structossia_1_1easing_1_1exponential_out.html", "structossia_1_1easing_1_1exponential_out" ],
        [ "exponentialInOut", "structossia_1_1easing_1_1exponential_in_out.html", "structossia_1_1easing_1_1exponential_in_out" ],
        [ "elasticIn", "structossia_1_1easing_1_1elastic_in.html", "structossia_1_1easing_1_1elastic_in" ],
        [ "elasticOut", "structossia_1_1easing_1_1elastic_out.html", "structossia_1_1easing_1_1elastic_out" ],
        [ "elasticInOut", "structossia_1_1easing_1_1elastic_in_out.html", "structossia_1_1easing_1_1elastic_in_out" ],
        [ "backIn", "structossia_1_1easing_1_1back_in.html", "structossia_1_1easing_1_1back_in" ],
        [ "backOut", "structossia_1_1easing_1_1back_out.html", "structossia_1_1easing_1_1back_out" ],
        [ "backInOut", "structossia_1_1easing_1_1back_in_out.html", "structossia_1_1easing_1_1back_in_out" ],
        [ "bounceOut", "structossia_1_1easing_1_1bounce_out.html", "structossia_1_1easing_1_1bounce_out" ],
        [ "bounceIn", "structossia_1_1easing_1_1bounce_in.html", "structossia_1_1easing_1_1bounce_in" ],
        [ "bounceInOut", "structossia_1_1easing_1_1bounce_in_out.html", "structossia_1_1easing_1_1bounce_in_out" ],
        [ "perlinInOut", "structossia_1_1easing_1_1perlin_in_out.html", "structossia_1_1easing_1_1perlin_in_out" ]
      ] ],
      [ "expressions", null, [
        [ "expression_atom", "classossia_1_1expressions_1_1expression__atom.html", "classossia_1_1expressions_1_1expression__atom" ],
        [ "expression_bool", "classossia_1_1expressions_1_1expression__bool.html", "classossia_1_1expressions_1_1expression__bool" ],
        [ "expression_composition", "classossia_1_1expressions_1_1expression__composition.html", "classossia_1_1expressions_1_1expression__composition" ],
        [ "expression_not", "classossia_1_1expressions_1_1expression__not.html", "classossia_1_1expressions_1_1expression__not" ],
        [ "expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", "classossia_1_1expressions_1_1expression__pulse" ]
      ] ],
      [ "java", null, [
        [ "Value", "classossia_1_1java_1_1_value.html", "classossia_1_1java_1_1_value" ]
      ] ],
      [ "minuit", null, [
        [ "name_table", "classossia_1_1minuit_1_1name__table.html", "classossia_1_1minuit_1_1name__table" ],
        [ "minuit_behavior", "structossia_1_1minuit_1_1minuit__behavior.html", "structossia_1_1minuit_1_1minuit__behavior" ],
        [ "minuit_behavior< minuit_command::Error, Op >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01_op_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01_op_01_4" ],
        [ "minuit_behavior< minuit_command::Error, minuit_operation::Get >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01minuit__operation_1_1_get_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01minuit__operation_1_1_get_01_4" ],
        [ "minuit_behavior< minuit_command::Request, minuit_operation::Get >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_get_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_get_01_4" ],
        [ "minuit_behavior< minuit_command::Request, minuit_operation::Listen >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_listen_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_listen_01_4" ],
        [ "minuit_behavior< minuit_command::Request, minuit_operation::Namespace >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_namespace_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_namespace_01_4" ],
        [ "minuit_behavior< minuit_command::Answer, minuit_operation::Listen >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_listen_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_listen_01_4" ],
        [ "minuit_behavior< minuit_command::Answer, minuit_operation::Get >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_get_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_get_01_4" ],
        [ "minuit_behavior< minuit_command::Answer, minuit_operation::Namespace >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_namespace_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_namespace_01_4" ],
        [ "minuit_message_handler", "classossia_1_1minuit_1_1minuit__message__handler.html", null ]
      ] ],
      [ "net", null, [
        [ "detail", null, [
          [ "domain_min_visitor_helper", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper.html", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper" ],
          [ "domain_min_visitor_helper< domain_base< Impulse > >", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01_impulse_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01_impulse_01_4_01_4" ],
          [ "domain_min_visitor_helper< domain_base< std::string > >", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01std_1_1string_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01std_1_1string_01_4_01_4" ],
          [ "domain_min_visitor_helper< domain_base< ossia::value > >", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01ossia_1_1value_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__min__visitor__helper_3_01domain__base_3_01ossia_1_1value_01_4_01_4" ],
          [ "domain_max_visitor_helper", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper.html", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper" ],
          [ "domain_max_visitor_helper< domain_base< Impulse > >", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01_impulse_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01_impulse_01_4_01_4" ],
          [ "domain_max_visitor_helper< domain_base< std::string > >", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01std_1_1string_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01std_1_1string_01_4_01_4" ],
          [ "domain_max_visitor_helper< domain_base< ossia::value > >", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01ossia_1_1value_01_4_01_4.html", "structossia_1_1net_1_1detail_1_1domain__max__visitor__helper_3_01domain__base_3_01ossia_1_1value_01_4_01_4" ]
        ] ],
        [ "midi", null, [
          [ "midi_channel", "structossia_1_1net_1_1midi_1_1midi__channel.html", "structossia_1_1net_1_1midi_1_1midi__channel" ],
          [ "note_on_N_node", "classossia_1_1net_1_1midi_1_1note__on___n__node.html", "classossia_1_1net_1_1midi_1_1note__on___n__node" ],
          [ "note_off_N_node", "classossia_1_1net_1_1midi_1_1note__off___n__node.html", "classossia_1_1net_1_1midi_1_1note__off___n__node" ],
          [ "control_N_node", "classossia_1_1net_1_1midi_1_1control___n__node.html", "classossia_1_1net_1_1midi_1_1control___n__node" ],
          [ "program_N_node", "classossia_1_1net_1_1midi_1_1program___n__node.html", "classossia_1_1net_1_1midi_1_1program___n__node" ],
          [ "program_node", "classossia_1_1net_1_1midi_1_1program__node.html", "classossia_1_1net_1_1midi_1_1program__node" ],
          [ "note_on_node", "classossia_1_1net_1_1midi_1_1note__on__node.html", "classossia_1_1net_1_1midi_1_1note__on__node" ],
          [ "note_off_node", "classossia_1_1net_1_1midi_1_1note__off__node.html", "classossia_1_1net_1_1midi_1_1note__off__node" ],
          [ "control_node", "classossia_1_1net_1_1midi_1_1control__node.html", "classossia_1_1net_1_1midi_1_1control__node" ],
          [ "channel_node", "classossia_1_1net_1_1midi_1_1channel__node.html", "classossia_1_1net_1_1midi_1_1channel__node" ],
          [ "address_info", "structossia_1_1net_1_1midi_1_1address__info.html", "structossia_1_1net_1_1midi_1_1address__info" ],
          [ "midi_address", "classossia_1_1net_1_1midi_1_1midi__address.html", "classossia_1_1net_1_1midi_1_1midi__address" ],
          [ "midi_device", "classossia_1_1net_1_1midi_1_1midi__device.html", "classossia_1_1net_1_1midi_1_1midi__device" ],
          [ "midi_name_table", "structossia_1_1net_1_1midi_1_1midi__name__table.html", "structossia_1_1net_1_1midi_1_1midi__name__table" ],
          [ "midi_node", "classossia_1_1net_1_1midi_1_1midi__node.html", "classossia_1_1net_1_1midi_1_1midi__node" ],
          [ "midi_info", "structossia_1_1net_1_1midi_1_1midi__info.html", "structossia_1_1net_1_1midi_1_1midi__info" ],
          [ "midi_protocol", "classossia_1_1net_1_1midi_1_1midi__protocol.html", "classossia_1_1net_1_1midi_1_1midi__protocol" ]
        ] ],
        [ "address_base", "classossia_1_1net_1_1address__base.html", "classossia_1_1net_1_1address__base" ],
        [ "device_capabilities", "structossia_1_1net_1_1device__capabilities.html", "structossia_1_1net_1_1device__capabilities" ],
        [ "device_base", "classossia_1_1net_1_1device__base.html", "classossia_1_1net_1_1device__base" ],
        [ "node_base", "classossia_1_1net_1_1node__base.html", "classossia_1_1net_1_1node__base" ],
        [ "protocol_base", "classossia_1_1net_1_1protocol__base.html", "classossia_1_1net_1_1protocol__base" ],
        [ "network_logger", "classossia_1_1net_1_1network__logger.html", "classossia_1_1net_1_1network__logger" ],
        [ "apply_domain_visitor", "structossia_1_1net_1_1apply__domain__visitor.html", "structossia_1_1net_1_1apply__domain__visitor" ],
        [ "tuple_apply_domain_helper", "structossia_1_1net_1_1tuple__apply__domain__helper.html", "structossia_1_1net_1_1tuple__apply__domain__helper" ],
        [ "tuple_clamp", "structossia_1_1net_1_1tuple__clamp.html", "structossia_1_1net_1_1tuple__clamp" ],
        [ "vec_clamp", "structossia_1_1net_1_1vec__clamp.html", "structossia_1_1net_1_1vec__clamp" ],
        [ "generic_clamp", "structossia_1_1net_1_1generic__clamp.html", "structossia_1_1net_1_1generic__clamp" ],
        [ "domain_min_visitor", "structossia_1_1net_1_1domain__min__visitor.html", "structossia_1_1net_1_1domain__min__visitor" ],
        [ "domain_max_visitor", "structossia_1_1net_1_1domain__max__visitor.html", "structossia_1_1net_1_1domain__max__visitor" ],
        [ "domain_set_min_visitor", "structossia_1_1net_1_1domain__set__min__visitor.html", "structossia_1_1net_1_1domain__set__min__visitor" ],
        [ "domain_set_max_visitor", "structossia_1_1net_1_1domain__set__max__visitor.html", "structossia_1_1net_1_1domain__set__max__visitor" ],
        [ "domain_minmax_creation_visitor", "structossia_1_1net_1_1domain__minmax__creation__visitor.html", "structossia_1_1net_1_1domain__minmax__creation__visitor" ],
        [ "domain_value_set_creation_visitor", "structossia_1_1net_1_1domain__value__set__creation__visitor.html", "structossia_1_1net_1_1domain__value__set__creation__visitor" ],
        [ "domain_base", "structossia_1_1net_1_1domain__base.html", "structossia_1_1net_1_1domain__base" ],
        [ "numeric_clamp", "structossia_1_1net_1_1numeric__clamp.html", "structossia_1_1net_1_1numeric__clamp" ],
        [ "value_set_clamp", "structossia_1_1net_1_1value__set__clamp.html", "structossia_1_1net_1_1value__set__clamp" ],
        [ "domain_base< Impulse >", "structossia_1_1net_1_1domain__base_3_01_impulse_01_4.html", null ],
        [ "domain_base< std::string >", "structossia_1_1net_1_1domain__base_3_01std_1_1string_01_4.html", "structossia_1_1net_1_1domain__base_3_01std_1_1string_01_4" ],
        [ "domain_base< std::vector< ossia::value > >", "structossia_1_1net_1_1domain__base_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4.html", "structossia_1_1net_1_1domain__base_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4" ],
        [ "domain_base< std::array< float, N > >", "structossia_1_1net_1_1domain__base_3_01std_1_1array_3_01float_00_01_n_01_4_01_4.html", "structossia_1_1net_1_1domain__base_3_01std_1_1array_3_01float_00_01_n_01_4_01_4" ],
        [ "domain_base< ossia::value >", "structossia_1_1net_1_1domain__base_3_01ossia_1_1value_01_4.html", "structossia_1_1net_1_1domain__base_3_01ossia_1_1value_01_4" ],
        [ "domain", "structossia_1_1net_1_1domain.html", "structossia_1_1net_1_1domain" ],
        [ "domain_conversion", "structossia_1_1net_1_1domain__conversion.html", "structossia_1_1net_1_1domain__conversion" ],
        [ "domain_conversion< domain_base< Impulse > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_impulse_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_impulse_01_4_01_4" ],
        [ "domain_conversion< domain_base< std::vector< ossia::value > > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4_01_4" ],
        [ "domain_conversion< domain_base< std::array< float, N > > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1array_3_01float_00_01_n_01_4_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1array_3_01float_00_01_n_01_4_01_4_01_4" ],
        [ "domain_conversion< domain_base< std::string > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1string_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01std_1_1string_01_4_01_4" ],
        [ "generic_address_data", "structossia_1_1net_1_1generic__address__data.html", "structossia_1_1net_1_1generic__address__data" ],
        [ "generic_address", "classossia_1_1net_1_1generic__address.html", "classossia_1_1net_1_1generic__address" ],
        [ "generic_device", "classossia_1_1net_1_1generic__device.html", "classossia_1_1net_1_1generic__device" ],
        [ "generic_node", "classossia_1_1net_1_1generic__node.html", "classossia_1_1net_1_1generic__node" ],
        [ "http_address", "classossia_1_1net_1_1http__address.html", "classossia_1_1net_1_1http__address" ],
        [ "http_address_data_base", "structossia_1_1net_1_1http__address__data__base.html", "structossia_1_1net_1_1http__address__data__base" ],
        [ "http_address_data", "structossia_1_1net_1_1http__address__data.html", "structossia_1_1net_1_1http__address__data" ],
        [ "http_device", "classossia_1_1net_1_1http__device.html", "classossia_1_1net_1_1http__device" ],
        [ "http_node", "classossia_1_1net_1_1http__node.html", "classossia_1_1net_1_1http__node" ],
        [ "http_protocol", "classossia_1_1net_1_1http__protocol.html", "classossia_1_1net_1_1http__protocol" ],
        [ "local_protocol", "classossia_1_1net_1_1local__protocol.html", "classossia_1_1net_1_1local__protocol" ],
        [ "minuit_protocol", "classossia_1_1net_1_1minuit__protocol.html", "classossia_1_1net_1_1minuit__protocol" ],
        [ "minuit_connection_data", "structossia_1_1net_1_1minuit__connection__data.html", "structossia_1_1net_1_1minuit__connection__data" ],
        [ "zeroconf_server", "structossia_1_1net_1_1zeroconf__server.html", "structossia_1_1net_1_1zeroconf__server" ],
        [ "osc_outbound_visitor", "structossia_1_1net_1_1osc__outbound__visitor.html", "structossia_1_1net_1_1osc__outbound__visitor" ],
        [ "osc_utilities", "structossia_1_1net_1_1osc__utilities.html", null ],
        [ "osc_inbound_visitor", "structossia_1_1net_1_1osc__inbound__visitor.html", "structossia_1_1net_1_1osc__inbound__visitor" ],
        [ "osc_inbound_numeric_visitor", "structossia_1_1net_1_1osc__inbound__numeric__visitor.html", "structossia_1_1net_1_1osc__inbound__numeric__visitor" ],
        [ "osc_inbound_impulse_visitor", "structossia_1_1net_1_1osc__inbound__impulse__visitor.html", "structossia_1_1net_1_1osc__inbound__impulse__visitor" ],
        [ "osc_write_domain_visitor", "structossia_1_1net_1_1osc__write__domain__visitor.html", "structossia_1_1net_1_1osc__write__domain__visitor" ],
        [ "osc_protocol", "classossia_1_1net_1_1osc__protocol.html", "classossia_1_1net_1_1osc__protocol" ],
        [ "serial_address", "classossia_1_1net_1_1serial__address.html", "classossia_1_1net_1_1serial__address" ],
        [ "serial_address_data_base", "structossia_1_1net_1_1serial__address__data__base.html", "structossia_1_1net_1_1serial__address__data__base" ],
        [ "serial_address_data", "structossia_1_1net_1_1serial__address__data.html", "structossia_1_1net_1_1serial__address__data" ],
        [ "serial_device", "classossia_1_1net_1_1serial__device.html", "classossia_1_1net_1_1serial__device" ],
        [ "serial_node", "classossia_1_1net_1_1serial__node.html", "classossia_1_1net_1_1serial__node" ],
        [ "serial_wrapper", "classossia_1_1net_1_1serial__wrapper.html", "classossia_1_1net_1_1serial__wrapper" ],
        [ "serial_protocol", "classossia_1_1net_1_1serial__protocol.html", "classossia_1_1net_1_1serial__protocol" ],
        [ "ws_generic_client_address", "classossia_1_1net_1_1ws__generic__client__address.html", "classossia_1_1net_1_1ws__generic__client__address" ],
        [ "ws_generic_client_address_data_base", "structossia_1_1net_1_1ws__generic__client__address__data__base.html", "structossia_1_1net_1_1ws__generic__client__address__data__base" ],
        [ "ws_generic_client_address_data", "structossia_1_1net_1_1ws__generic__client__address__data.html", "structossia_1_1net_1_1ws__generic__client__address__data" ],
        [ "ws_generic_client_device", "classossia_1_1net_1_1ws__generic__client__device.html", "classossia_1_1net_1_1ws__generic__client__device" ],
        [ "ws_generic_client_node", "classossia_1_1net_1_1ws__generic__client__node.html", "classossia_1_1net_1_1ws__generic__client__node" ],
        [ "ws_generic_client_protocol", "classossia_1_1net_1_1ws__generic__client__protocol.html", "classossia_1_1net_1_1ws__generic__client__protocol" ]
      ] ],
      [ "context", "structossia_1_1context.html", "structossia_1_1context" ],
      [ "invalid_callback_error", "structossia_1_1invalid__callback__error.html", "structossia_1_1invalid__callback__error" ],
      [ "callback_container", "classossia_1_1callback__container.html", "classossia_1_1callback__container" ],
      [ "computeValue_visitor", "structossia_1_1compute_value__visitor.html", "structossia_1_1compute_value__visitor" ],
      [ "automation", "classossia_1_1automation.html", "classossia_1_1automation" ],
      [ "behavior", "structossia_1_1behavior.html", "structossia_1_1behavior" ],
      [ "curve", "classossia_1_1curve.html", "classossia_1_1curve" ],
      [ "constant_curve", "classossia_1_1constant__curve.html", "classossia_1_1constant__curve" ],
      [ "curve_abstract", "classossia_1_1curve__abstract.html", "classossia_1_1curve__abstract" ],
      [ "curve_segment_ease", "structossia_1_1curve__segment__ease.html", "structossia_1_1curve__segment__ease" ],
      [ "curve_segment_empty", "structossia_1_1curve__segment__empty.html", "structossia_1_1curve__segment__empty" ],
      [ "curve_segment_linear", "structossia_1_1curve__segment__linear.html", "structossia_1_1curve__segment__linear" ],
      [ "curve_segment_power", "structossia_1_1curve__segment__power.html", "structossia_1_1curve__segment__power" ],
      [ "curve_segment_sin", "structossia_1_1curve__segment__sin.html", "structossia_1_1curve__segment__sin" ],
      [ "angle_unit", "structossia_1_1angle__unit.html", "structossia_1_1angle__unit" ],
      [ "radian_u", "structossia_1_1radian__u.html", null ],
      [ "degree_u", "structossia_1_1degree__u.html", null ],
      [ "dataspace_traits< angle_u >", "structossia_1_1dataspace__traits_3_01angle__u_01_4.html", null ],
      [ "color_unit", "structossia_1_1color__unit.html", "structossia_1_1color__unit" ],
      [ "argb_u", "structossia_1_1argb__u.html", "structossia_1_1argb__u" ],
      [ "rgba_u", "structossia_1_1rgba__u.html", "structossia_1_1rgba__u" ],
      [ "rgb_u", "structossia_1_1rgb__u.html", "structossia_1_1rgb__u" ],
      [ "bgr_u", "structossia_1_1bgr__u.html", "structossia_1_1bgr__u" ],
      [ "argb8_u", "structossia_1_1argb8__u.html", "structossia_1_1argb8__u" ],
      [ "hsv_u", "structossia_1_1hsv__u.html", "structossia_1_1hsv__u" ],
      [ "hsl_u", "structossia_1_1hsl__u.html", "structossia_1_1hsl__u" ],
      [ "cmy8_u", "structossia_1_1cmy8__u.html", "structossia_1_1cmy8__u" ],
      [ "cmyk8_u", "structossia_1_1cmyk8__u.html", "structossia_1_1cmyk8__u" ],
      [ "xyz_u", "structossia_1_1xyz__u.html", "structossia_1_1xyz__u" ],
      [ "yxy_u", "structossia_1_1yxy__u.html", "structossia_1_1yxy__u" ],
      [ "hunter_lab_u", "structossia_1_1hunter__lab__u.html", "structossia_1_1hunter__lab__u" ],
      [ "cie_lab_u", "structossia_1_1cie__lab__u.html", "structossia_1_1cie__lab__u" ],
      [ "cie_luv_u", "structossia_1_1cie__luv__u.html", "structossia_1_1cie__luv__u" ],
      [ "dataspace_traits< color_u >", "structossia_1_1dataspace__traits_3_01color__u_01_4.html", null ],
      [ "unit_t", "structossia_1_1unit__t.html", "structossia_1_1unit__t" ],
      [ "is_unit", "structossia_1_1is__unit.html", null ],
      [ "strong_value", "structossia_1_1strong__value.html", "structossia_1_1strong__value" ],
      [ "linear_unit", "structossia_1_1linear__unit.html", null ],
      [ "unit_traits", "structossia_1_1unit__traits.html", null ],
      [ "unit_traits< strong_value< T > >", "structossia_1_1unit__traits_3_01strong__value_3_01_t_01_4_01_4.html", null ],
      [ "dataspace_traits", "structossia_1_1dataspace__traits.html", null ],
      [ "distance_ratio", "structossia_1_1distance__ratio.html", null ],
      [ "speed_ratio", "structossia_1_1speed__ratio.html", null ],
      [ "merger_impl", "structossia_1_1merger__impl.html", "structossia_1_1merger__impl" ],
      [ "vec_merger_impl_helper", "structossia_1_1vec__merger__impl__helper.html", "structossia_1_1vec__merger__impl__helper" ],
      [ "vec_merger_impl", "structossia_1_1vec__merger__impl.html", "structossia_1_1vec__merger__impl" ],
      [ "make_unit_helper", "classossia_1_1make__unit__helper.html", "classossia_1_1make__unit__helper" ],
      [ "make_value_helper", "structossia_1_1make__value__helper.html", null ],
      [ "make_value_helper< U, float >", "structossia_1_1make__value__helper_3_01_u_00_01float_01_4.html", "structossia_1_1make__value__helper_3_01_u_00_01float_01_4" ],
      [ "make_value_helper< U, ossia::Vec2f >", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec2f_01_4.html", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec2f_01_4" ],
      [ "make_value_helper< U, ossia::Vec3f >", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec3f_01_4.html", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec3f_01_4" ],
      [ "make_value_helper< U, ossia::Vec4f >", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec4f_01_4.html", "structossia_1_1make__value__helper_3_01_u_00_01ossia_1_1_vec4f_01_4" ],
      [ "make_value_with_unit_visitor", "structossia_1_1make__value__with__unit__visitor.html", "structossia_1_1make__value__with__unit__visitor" ],
      [ "distance_unit", "structossia_1_1distance__unit.html", "structossia_1_1distance__unit" ],
      [ "unit_traits< meter_u >", "structossia_1_1unit__traits_3_01meter__u_01_4.html", null ],
      [ "unit_traits< kilometer_u >", "structossia_1_1unit__traits_3_01kilometer__u_01_4.html", null ],
      [ "unit_traits< decimeter_u >", "structossia_1_1unit__traits_3_01decimeter__u_01_4.html", null ],
      [ "unit_traits< centimeter_u >", "structossia_1_1unit__traits_3_01centimeter__u_01_4.html", null ],
      [ "unit_traits< millimeter_u >", "structossia_1_1unit__traits_3_01millimeter__u_01_4.html", null ],
      [ "unit_traits< micrometer_u >", "structossia_1_1unit__traits_3_01micrometer__u_01_4.html", null ],
      [ "unit_traits< nanometer_u >", "structossia_1_1unit__traits_3_01nanometer__u_01_4.html", null ],
      [ "unit_traits< picometer_u >", "structossia_1_1unit__traits_3_01picometer__u_01_4.html", null ],
      [ "unit_traits< inch_u >", "structossia_1_1unit__traits_3_01inch__u_01_4.html", null ],
      [ "unit_traits< foot_u >", "structossia_1_1unit__traits_3_01foot__u_01_4.html", null ],
      [ "unit_traits< mile_u >", "structossia_1_1unit__traits_3_01mile__u_01_4.html", null ],
      [ "dataspace_traits< distance_u >", "structossia_1_1dataspace__traits_3_01distance__u_01_4.html", null ],
      [ "gain_unit", "structossia_1_1gain__unit.html", "structossia_1_1gain__unit" ],
      [ "linear_u", "structossia_1_1linear__u.html", null ],
      [ "midigain_u", "structossia_1_1midigain__u.html", null ],
      [ "decibel_u", "structossia_1_1decibel__u.html", null ],
      [ "decibel_raw_u", "structossia_1_1decibel__raw__u.html", null ],
      [ "dataspace_traits< gain_u >", "structossia_1_1dataspace__traits_3_01gain__u_01_4.html", null ],
      [ "orientation_unit", "structossia_1_1orientation__unit.html", "structossia_1_1orientation__unit" ],
      [ "quaternion_u", "structossia_1_1quaternion__u.html", "structossia_1_1quaternion__u" ],
      [ "euler_u", "structossia_1_1euler__u.html", "structossia_1_1euler__u" ],
      [ "axis_u", "structossia_1_1axis__u.html", "structossia_1_1axis__u" ],
      [ "dataspace_traits< orientation_u >", "structossia_1_1dataspace__traits_3_01orientation__u_01_4.html", null ],
      [ "position_unit", "structossia_1_1position__unit.html", "structossia_1_1position__unit" ],
      [ "cartesian_3d_u", "structossia_1_1cartesian__3d__u.html", "structossia_1_1cartesian__3d__u" ],
      [ "cartesian_2d_u", "structossia_1_1cartesian__2d__u.html", "structossia_1_1cartesian__2d__u" ],
      [ "spherical_u", "structossia_1_1spherical__u.html", "structossia_1_1spherical__u" ],
      [ "polar_u", "structossia_1_1polar__u.html", "structossia_1_1polar__u" ],
      [ "opengl_u", "structossia_1_1opengl__u.html", "structossia_1_1opengl__u" ],
      [ "cylindrical_u", "structossia_1_1cylindrical__u.html", "structossia_1_1cylindrical__u" ],
      [ "dataspace_traits< position_u >", "structossia_1_1dataspace__traits_3_01position__u_01_4.html", null ],
      [ "speed_unit", "structossia_1_1speed__unit.html", "structossia_1_1speed__unit" ],
      [ "unit_traits< meter_per_second_u >", "structossia_1_1unit__traits_3_01meter__per__second__u_01_4.html", null ],
      [ "unit_traits< miles_per_hour_u >", "structossia_1_1unit__traits_3_01miles__per__hour__u_01_4.html", null ],
      [ "unit_traits< kilometer_per_hour_u >", "structossia_1_1unit__traits_3_01kilometer__per__hour__u_01_4.html", null ],
      [ "unit_traits< knot_u >", "structossia_1_1unit__traits_3_01knot__u_01_4.html", null ],
      [ "unit_traits< foot_per_hour_u >", "structossia_1_1unit__traits_3_01foot__per__hour__u_01_4.html", null ],
      [ "unit_traits< foot_per_second_u >", "structossia_1_1unit__traits_3_01foot__per__second__u_01_4.html", null ],
      [ "dataspace_traits< speed_u >", "structossia_1_1dataspace__traits_3_01speed__u_01_4.html", null ],
      [ "time_unit", "structossia_1_1time__unit.html", "structossia_1_1time__unit" ],
      [ "second_u", "structossia_1_1second__u.html", null ],
      [ "bark_u", "structossia_1_1bark__u.html", null ],
      [ "bpm_u", "structossia_1_1bpm__u.html", null ],
      [ "cent_u", "structossia_1_1cent__u.html", null ],
      [ "frequency_u", "structossia_1_1frequency__u.html", null ],
      [ "mel_u", "structossia_1_1mel__u.html", null ],
      [ "midi_pitch_u", "structossia_1_1midi__pitch__u.html", null ],
      [ "millisecond_u", "structossia_1_1millisecond__u.html", null ],
      [ "playback_speed_u", "structossia_1_1playback__speed__u.html", null ],
      [ "dataspace_traits< time_u >", "structossia_1_1dataspace__traits_3_01time__u_01_4.html", null ],
      [ "value_with_unit", "structossia_1_1value__with__unit.html", "structossia_1_1value__with__unit" ],
      [ "execution_error", "structossia_1_1execution__error.html", "structossia_1_1execution__error" ],
      [ "invalid_value_type_error", "structossia_1_1invalid__value__type__error.html", "structossia_1_1invalid__value__type__error" ],
      [ "invalid_access_error", "structossia_1_1invalid__access__error.html", "structossia_1_1invalid__access__error" ],
      [ "loop", "classossia_1_1loop.html", "classossia_1_1loop" ],
      [ "mapper_compute_visitor", "structossia_1_1mapper__compute__visitor.html", "structossia_1_1mapper__compute__visitor" ],
      [ "mapper", "classossia_1_1mapper.html", "classossia_1_1mapper" ],
      [ "clock", "classossia_1_1clock.html", "classossia_1_1clock" ],
      [ "scenario", "classossia_1_1scenario.html", "classossia_1_1scenario" ],
      [ "time_constraint", "classossia_1_1time__constraint.html", "classossia_1_1time__constraint" ],
      [ "time_event", "classossia_1_1time__event.html", "classossia_1_1time__event" ],
      [ "time_node", "classossia_1_1time__node.html", "classossia_1_1time__node" ],
      [ "time_process", "classossia_1_1time__process.html", "classossia_1_1time__process" ],
      [ "time_value", "classossia_1_1time__value.html", "classossia_1_1time__value" ],
      [ "custom_state", "classossia_1_1custom__state.html", "classossia_1_1custom__state" ],
      [ "destination_qualifiers", "structossia_1_1destination__qualifiers.html", "structossia_1_1destination__qualifiers" ],
      [ "state_execution_visitor", "structossia_1_1state__execution__visitor.html", "structossia_1_1state__execution__visitor" ],
      [ "vec_merger", "structossia_1_1vec__merger.html", "structossia_1_1vec__merger" ],
      [ "state_flatten_visitor_merger", "structossia_1_1state__flatten__visitor__merger.html", "structossia_1_1state__flatten__visitor__merger" ],
      [ "state_flatten_visitor", "structossia_1_1state__flatten__visitor.html", "structossia_1_1state__flatten__visitor" ],
      [ "state_print_visitor", "structossia_1_1state__print__visitor.html", "structossia_1_1state__print__visitor" ],
      [ "functional_state", "classossia_1_1functional__state.html", "classossia_1_1functional__state" ],
      [ "functional_state_composition", "classossia_1_1functional__state__composition.html", "classossia_1_1functional__state__composition" ],
      [ "message", "structossia_1_1message.html", "structossia_1_1message" ],
      [ "piecewise_message", "structossia_1_1piecewise__message.html", "structossia_1_1piecewise__message" ],
      [ "piecewise_vec_message", "structossia_1_1piecewise__vec__message.html", "structossia_1_1piecewise__vec__message" ],
      [ "state", "classossia_1_1state.html", "classossia_1_1state" ],
      [ "Destination", "classossia_1_1_destination.html", "classossia_1_1_destination" ],
      [ "Impulse", "structossia_1_1_impulse.html", "structossia_1_1_impulse" ],
      [ "value_comparison_visitor", "structossia_1_1value__comparison__visitor.html", "structossia_1_1value__comparison__visitor" ],
      [ "value_comparison_visitor2", "structossia_1_1value__comparison__visitor2.html", "structossia_1_1value__comparison__visitor2" ],
      [ "partial_lhs_value_comparison_visitor2", "structossia_1_1partial__lhs__value__comparison__visitor2.html", "structossia_1_1partial__lhs__value__comparison__visitor2" ],
      [ "partial_rhs_value_comparison_visitor2", "structossia_1_1partial__rhs__value__comparison__visitor2.html", "structossia_1_1partial__rhs__value__comparison__visitor2" ],
      [ "value_variant", "structossia_1_1value__variant.html", null ],
      [ "value", "classossia_1_1value.html", "classossia_1_1value" ],
      [ "value_merger", "structossia_1_1value__merger.html", null ],
      [ "value_trait", "structossia_1_1value__trait.html", null ],
      [ "value_trait< ossia::Impulse >", "structossia_1_1value__trait_3_01ossia_1_1_impulse_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_impulse_01_4" ],
      [ "value_trait< int32_t >", "structossia_1_1value__trait_3_01int32__t_01_4.html", "structossia_1_1value__trait_3_01int32__t_01_4" ],
      [ "value_trait< float >", "structossia_1_1value__trait_3_01float_01_4.html", "structossia_1_1value__trait_3_01float_01_4" ],
      [ "value_trait< bool >", "structossia_1_1value__trait_3_01bool_01_4.html", "structossia_1_1value__trait_3_01bool_01_4" ],
      [ "value_trait< char >", "structossia_1_1value__trait_3_01char_01_4.html", "structossia_1_1value__trait_3_01char_01_4" ],
      [ "value_trait< std::string >", "structossia_1_1value__trait_3_01std_1_1string_01_4.html", "structossia_1_1value__trait_3_01std_1_1string_01_4" ],
      [ "value_trait< std::vector< ossia::value > >", "structossia_1_1value__trait_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4.html", "structossia_1_1value__trait_3_01std_1_1vector_3_01ossia_1_1value_01_4_01_4" ],
      [ "value_trait< ossia::Destination >", "structossia_1_1value__trait_3_01ossia_1_1_destination_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_destination_01_4" ],
      [ "value_trait< ossia::Vec2f >", "structossia_1_1value__trait_3_01ossia_1_1_vec2f_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec2f_01_4" ],
      [ "value_trait< ossia::Vec3f >", "structossia_1_1value__trait_3_01ossia_1_1_vec3f_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec3f_01_4" ],
      [ "value_trait< ossia::Vec4f >", "structossia_1_1value__trait_3_01ossia_1_1_vec4f_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec4f_01_4" ],
      [ "value_trait< ossia::value >", "structossia_1_1value__trait_3_01ossia_1_1value_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1value_01_4" ],
      [ "apply_ternary_fun_visitor", "structossia_1_1apply__ternary__fun__visitor.html", "structossia_1_1apply__ternary__fun__visitor" ],
      [ "apply_binary_fun_visitor", "structossia_1_1apply__binary__fun__visitor.html", "structossia_1_1apply__binary__fun__visitor" ],
      [ "clamp_functor", "structossia_1_1clamp__functor.html", null ],
      [ "clamp_min_functor", "structossia_1_1clamp__min__functor.html", null ],
      [ "clamp_max_functor", "structossia_1_1clamp__max__functor.html", null ],
      [ "wrap_functor", "structossia_1_1wrap__functor.html", null ],
      [ "fold_functor", "structossia_1_1fold__functor.html", null ],
      [ "parse_error", "structossia_1_1parse__error.html", "structossia_1_1parse__error" ],
      [ "connection_error", "structossia_1_1connection__error.html", "structossia_1_1connection__error" ],
      [ "invalid_node_error", "structossia_1_1invalid__node__error.html", "structossia_1_1invalid__node__error" ],
      [ "ossiaException", "classossia_1_1ossia_exception.html", "classossia_1_1ossia_exception" ],
      [ "ossiaException_InvalidJSON", "classossia_1_1ossia_exception___invalid_j_s_o_n.html", "classossia_1_1ossia_exception___invalid_j_s_o_n" ],
      [ "ossiaException_InvalidXML", "classossia_1_1ossia_exception___invalid_x_m_l.html", "classossia_1_1ossia_exception___invalid_x_m_l" ],
      [ "ossiaException_InvalidAddress", "classossia_1_1ossia_exception___invalid_address.html", "classossia_1_1ossia_exception___invalid_address" ]
    ] ],
    [ "std", null, [
      [ "hash< ossia::distance_u >", "structstd_1_1hash_3_01ossia_1_1distance__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1distance__u_01_4" ],
      [ "hash< ossia::position_u >", "structstd_1_1hash_3_01ossia_1_1position__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1position__u_01_4" ],
      [ "hash< ossia::speed_u >", "structstd_1_1hash_3_01ossia_1_1speed__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1speed__u_01_4" ],
      [ "hash< ossia::orientation_u >", "structstd_1_1hash_3_01ossia_1_1orientation__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1orientation__u_01_4" ],
      [ "hash< ossia::angle_u >", "structstd_1_1hash_3_01ossia_1_1angle__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1angle__u_01_4" ],
      [ "hash< ossia::color_u >", "structstd_1_1hash_3_01ossia_1_1color__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1color__u_01_4" ],
      [ "hash< ossia::gain_u >", "structstd_1_1hash_3_01ossia_1_1gain__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1gain__u_01_4" ],
      [ "hash< ossia::time_u >", "structstd_1_1hash_3_01ossia_1_1time__u_01_4.html", "structstd_1_1hash_3_01ossia_1_1time__u_01_4" ]
    ] ],
    [ "tinyformat", null, [
      [ "detail", null, [
        [ "is_convertible", "structtinyformat_1_1detail_1_1is__convertible.html", null ],
        [ "is_wchar", "structtinyformat_1_1detail_1_1is__wchar.html", "structtinyformat_1_1detail_1_1is__wchar" ],
        [ "is_wchar< wchar_t * >", "structtinyformat_1_1detail_1_1is__wchar_3_01wchar__t_01_5_01_4.html", null ],
        [ "is_wchar< const wchar_t * >", "structtinyformat_1_1detail_1_1is__wchar_3_01const_01wchar__t_01_5_01_4.html", null ],
        [ "is_wchar< const wchar_t[n]>", "structtinyformat_1_1detail_1_1is__wchar_3_01const_01wchar__t[n]_4.html", null ],
        [ "is_wchar< wchar_t[n]>", "structtinyformat_1_1detail_1_1is__wchar_3_01wchar__t[n]_4.html", null ],
        [ "formatValueAsType", "structtinyformat_1_1detail_1_1format_value_as_type.html", null ],
        [ "formatValueAsType< T, fmtT, true >", "structtinyformat_1_1detail_1_1format_value_as_type_3_01_t_00_01fmt_t_00_01true_01_4.html", null ],
        [ "convertToInt", "structtinyformat_1_1detail_1_1convert_to_int.html", null ],
        [ "convertToInt< T, true >", "structtinyformat_1_1detail_1_1convert_to_int_3_01_t_00_01true_01_4.html", null ],
        [ "FormatArg", "classtinyformat_1_1detail_1_1_format_arg.html", "classtinyformat_1_1detail_1_1_format_arg" ],
        [ "FormatListN", "classtinyformat_1_1detail_1_1_format_list_n.html", "classtinyformat_1_1detail_1_1_format_list_n" ],
        [ "FormatListN< 0 >", "classtinyformat_1_1detail_1_1_format_list_n_3_010_01_4.html", "classtinyformat_1_1detail_1_1_format_list_n_3_010_01_4" ]
      ] ],
      [ "FormatList", "classtinyformat_1_1_format_list.html", "classtinyformat_1_1_format_list" ]
    ] ],
    [ "Calculator", "struct_calculator.html", "struct_calculator" ],
    [ "ossia_device", "structossia__device.html", "structossia__device" ],
    [ "ossia_domain", "structossia__domain.html", "structossia__domain" ],
    [ "ossia_preset", "structossia__preset.html", "structossia__preset" ],
    [ "ossia_protocol", "structossia__protocol.html", "structossia__protocol" ],
    [ "ossia_value", "structossia__value.html", "structossia__value" ],
    [ "ossia_value_callback_index", "structossia__value__callback__index.html", "structossia__value__callback__index" ]
];