var namespaceossia =
[
    [ "comparisons", null, [
      [ "DestinationValue", "structossia_1_1comparisons_1_1_destination_value.html", null ],
      [ "DestinationVisitor", "structossia_1_1comparisons_1_1_destination_visitor.html", "structossia_1_1comparisons_1_1_destination_visitor" ],
      [ "Impulse_T", "structossia_1_1comparisons_1_1_impulse___t.html", "structossia_1_1comparisons_1_1_impulse___t" ],
      [ "NumericValue", "structossia_1_1comparisons_1_1_numeric_value.html", null ],
      [ "String_T", "structossia_1_1comparisons_1_1_string___t.html", "structossia_1_1comparisons_1_1_string___t" ],
      [ "StringValue", "structossia_1_1comparisons_1_1_string_value.html", null ],
      [ "TupleValue", "structossia_1_1comparisons_1_1_tuple_value.html", null ],
      [ "TupleVisitor", "structossia_1_1comparisons_1_1_tuple_visitor.html", "structossia_1_1comparisons_1_1_tuple_visitor" ],
      [ "VecValue", "structossia_1_1comparisons_1_1_vec_value.html", null ],
      [ "VecVisitor", "structossia_1_1comparisons_1_1_vec_visitor.html", "structossia_1_1comparisons_1_1_vec_visitor" ]
    ] ],
    [ "detail", null, [
      [ "automation_impl", "classossia_1_1detail_1_1automation__impl.html", "classossia_1_1detail_1_1automation__impl" ],
      [ "clock_impl", "classossia_1_1detail_1_1clock__impl.html", "classossia_1_1detail_1_1clock__impl" ],
      [ "curve_impl", "classossia_1_1detail_1_1curve__impl.html", "classossia_1_1detail_1_1curve__impl" ],
      [ "loop_impl", "classossia_1_1detail_1_1loop__impl.html", "classossia_1_1detail_1_1loop__impl" ],
      [ "mapper_impl", "classossia_1_1detail_1_1mapper__impl.html", "classossia_1_1detail_1_1mapper__impl" ],
      [ "scenario_impl", "classossia_1_1detail_1_1scenario__impl.html", "classossia_1_1detail_1_1scenario__impl" ],
      [ "time_constraint_impl", "classossia_1_1detail_1_1time__constraint__impl.html", "classossia_1_1detail_1_1time__constraint__impl" ],
      [ "time_event_impl", "classossia_1_1detail_1_1time__event__impl.html", "classossia_1_1detail_1_1time__event__impl" ],
      [ "time_node_impl", "classossia_1_1detail_1_1time__node__impl.html", "classossia_1_1detail_1_1time__node__impl" ],
      [ "time_process_impl", "classossia_1_1detail_1_1time__process__impl.html", "classossia_1_1detail_1_1time__process__impl" ]
    ] ],
    [ "easing", null, [
      [ "backIn", "structossia_1_1easing_1_1back_in.html", "structossia_1_1easing_1_1back_in" ],
      [ "backInOut", "structossia_1_1easing_1_1back_in_out.html", "structossia_1_1easing_1_1back_in_out" ],
      [ "backOut", "structossia_1_1easing_1_1back_out.html", "structossia_1_1easing_1_1back_out" ],
      [ "bounceIn", "structossia_1_1easing_1_1bounce_in.html", "structossia_1_1easing_1_1bounce_in" ],
      [ "bounceInOut", "structossia_1_1easing_1_1bounce_in_out.html", "structossia_1_1easing_1_1bounce_in_out" ],
      [ "bounceOut", "structossia_1_1easing_1_1bounce_out.html", "structossia_1_1easing_1_1bounce_out" ],
      [ "circularIn", "structossia_1_1easing_1_1circular_in.html", "structossia_1_1easing_1_1circular_in" ],
      [ "circularInOut", "structossia_1_1easing_1_1circular_in_out.html", "structossia_1_1easing_1_1circular_in_out" ],
      [ "circularOut", "structossia_1_1easing_1_1circular_out.html", "structossia_1_1easing_1_1circular_out" ],
      [ "cubicIn", "structossia_1_1easing_1_1cubic_in.html", "structossia_1_1easing_1_1cubic_in" ],
      [ "cubicInOut", "structossia_1_1easing_1_1cubic_in_out.html", "structossia_1_1easing_1_1cubic_in_out" ],
      [ "cubicOut", "structossia_1_1easing_1_1cubic_out.html", "structossia_1_1easing_1_1cubic_out" ],
      [ "ease", "structossia_1_1easing_1_1ease.html", "structossia_1_1easing_1_1ease" ],
      [ "elasticIn", "structossia_1_1easing_1_1elastic_in.html", "structossia_1_1easing_1_1elastic_in" ],
      [ "elasticInOut", "structossia_1_1easing_1_1elastic_in_out.html", "structossia_1_1easing_1_1elastic_in_out" ],
      [ "elasticOut", "structossia_1_1easing_1_1elastic_out.html", "structossia_1_1easing_1_1elastic_out" ],
      [ "exponentialIn", "structossia_1_1easing_1_1exponential_in.html", "structossia_1_1easing_1_1exponential_in" ],
      [ "exponentialInOut", "structossia_1_1easing_1_1exponential_in_out.html", "structossia_1_1easing_1_1exponential_in_out" ],
      [ "exponentialOut", "structossia_1_1easing_1_1exponential_out.html", "structossia_1_1easing_1_1exponential_out" ],
      [ "linear", "structossia_1_1easing_1_1linear.html", "structossia_1_1easing_1_1linear" ],
      [ "perlinInOut", "structossia_1_1easing_1_1perlin_in_out.html", "structossia_1_1easing_1_1perlin_in_out" ],
      [ "quadraticIn", "structossia_1_1easing_1_1quadratic_in.html", "structossia_1_1easing_1_1quadratic_in" ],
      [ "quadraticInOut", "structossia_1_1easing_1_1quadratic_in_out.html", "structossia_1_1easing_1_1quadratic_in_out" ],
      [ "quadraticOut", "structossia_1_1easing_1_1quadratic_out.html", "structossia_1_1easing_1_1quadratic_out" ],
      [ "quarticIn", "structossia_1_1easing_1_1quartic_in.html", "structossia_1_1easing_1_1quartic_in" ],
      [ "quarticInOut", "structossia_1_1easing_1_1quartic_in_out.html", "structossia_1_1easing_1_1quartic_in_out" ],
      [ "quarticOut", "structossia_1_1easing_1_1quartic_out.html", "structossia_1_1easing_1_1quartic_out" ],
      [ "quinticIn", "structossia_1_1easing_1_1quintic_in.html", "structossia_1_1easing_1_1quintic_in" ],
      [ "quinticInOut", "structossia_1_1easing_1_1quintic_in_out.html", "structossia_1_1easing_1_1quintic_in_out" ],
      [ "quinticOut", "structossia_1_1easing_1_1quintic_out.html", "structossia_1_1easing_1_1quintic_out" ],
      [ "sineIn", "structossia_1_1easing_1_1sine_in.html", "structossia_1_1easing_1_1sine_in" ],
      [ "sineInOut", "structossia_1_1easing_1_1sine_in_out.html", "structossia_1_1easing_1_1sine_in_out" ],
      [ "sineOut", "structossia_1_1easing_1_1sine_out.html", "structossia_1_1easing_1_1sine_out" ]
    ] ],
    [ "expressions", null, [
      [ "expression_atom", "classossia_1_1expressions_1_1expression__atom.html", "classossia_1_1expressions_1_1expression__atom" ],
      [ "expression_bool", "classossia_1_1expressions_1_1expression__bool.html", "classossia_1_1expressions_1_1expression__bool" ],
      [ "expression_composition", "classossia_1_1expressions_1_1expression__composition.html", "classossia_1_1expressions_1_1expression__composition" ],
      [ "expression_not", "classossia_1_1expressions_1_1expression__not.html", "classossia_1_1expressions_1_1expression__not" ],
      [ "expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", "classossia_1_1expressions_1_1expression__pulse" ]
    ] ],
    [ "minuit", null, [
      [ "minuit_behavior", "structossia_1_1minuit_1_1minuit__behavior.html", "structossia_1_1minuit_1_1minuit__behavior" ],
      [ "minuit_behavior< minuit_command::Answer, minuit_operation::Get >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_get_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_get_01_4" ],
      [ "minuit_behavior< minuit_command::Answer, minuit_operation::Listen >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_listen_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_listen_01_4" ],
      [ "minuit_behavior< minuit_command::Answer, minuit_operation::Namespace >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_namespace_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_answer_00_01minuit__operation_1_1_namespace_01_4" ],
      [ "minuit_behavior< minuit_command::Error, Op >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01_op_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_error_00_01_op_01_4" ],
      [ "minuit_behavior< minuit_command::Request, minuit_operation::Get >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_get_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_get_01_4" ],
      [ "minuit_behavior< minuit_command::Request, minuit_operation::Listen >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_listen_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_listen_01_4" ],
      [ "minuit_behavior< minuit_command::Request, minuit_operation::Namespace >", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_namespace_01_4.html", "structossia_1_1minuit_1_1minuit__behavior_3_01minuit__command_1_1_request_00_01minuit__operation_1_1_namespace_01_4" ],
      [ "minuit_message_handler", "classossia_1_1minuit_1_1minuit__message__handler.html", null ],
      [ "name_table", "classossia_1_1minuit_1_1name__table.html", "classossia_1_1minuit_1_1name__table" ]
    ] ],
    [ "net", null, [
      [ "midi", null, [
        [ "address_info", "structossia_1_1net_1_1midi_1_1address__info.html", "structossia_1_1net_1_1midi_1_1address__info" ],
        [ "channel_node", "classossia_1_1net_1_1midi_1_1channel__node.html", "classossia_1_1net_1_1midi_1_1channel__node" ],
        [ "control_N_node", "classossia_1_1net_1_1midi_1_1control___n__node.html", "classossia_1_1net_1_1midi_1_1control___n__node" ],
        [ "control_node", "classossia_1_1net_1_1midi_1_1control__node.html", "classossia_1_1net_1_1midi_1_1control__node" ],
        [ "midi_address", "classossia_1_1net_1_1midi_1_1midi__address.html", "classossia_1_1net_1_1midi_1_1midi__address" ],
        [ "midi_channel", "structossia_1_1net_1_1midi_1_1midi__channel.html", "structossia_1_1net_1_1midi_1_1midi__channel" ],
        [ "midi_device", "classossia_1_1net_1_1midi_1_1midi__device.html", "classossia_1_1net_1_1midi_1_1midi__device" ],
        [ "midi_info", "structossia_1_1net_1_1midi_1_1midi__info.html", "structossia_1_1net_1_1midi_1_1midi__info" ],
        [ "midi_node", "classossia_1_1net_1_1midi_1_1midi__node.html", "classossia_1_1net_1_1midi_1_1midi__node" ],
        [ "midi_protocol", "classossia_1_1net_1_1midi_1_1midi__protocol.html", "classossia_1_1net_1_1midi_1_1midi__protocol" ],
        [ "note_off_N_node", "classossia_1_1net_1_1midi_1_1note__off___n__node.html", "classossia_1_1net_1_1midi_1_1note__off___n__node" ],
        [ "note_off_node", "classossia_1_1net_1_1midi_1_1note__off__node.html", "classossia_1_1net_1_1midi_1_1note__off__node" ],
        [ "note_on_N_node", "classossia_1_1net_1_1midi_1_1note__on___n__node.html", "classossia_1_1net_1_1midi_1_1note__on___n__node" ],
        [ "note_on_node", "classossia_1_1net_1_1midi_1_1note__on__node.html", "classossia_1_1net_1_1midi_1_1note__on__node" ],
        [ "program_N_node", "classossia_1_1net_1_1midi_1_1program___n__node.html", "classossia_1_1net_1_1midi_1_1program___n__node" ],
        [ "program_node", "classossia_1_1net_1_1midi_1_1program__node.html", "classossia_1_1net_1_1midi_1_1program__node" ]
      ] ],
      [ "address_base", "classossia_1_1net_1_1address__base.html", "classossia_1_1net_1_1address__base" ],
      [ "device_base", "classossia_1_1net_1_1device__base.html", "classossia_1_1net_1_1device__base" ],
      [ "domain_base", "structossia_1_1net_1_1domain__base.html", "structossia_1_1net_1_1domain__base" ],
      [ "domain_base< Behavior >", "structossia_1_1net_1_1domain__base_3_01_behavior_01_4.html", "structossia_1_1net_1_1domain__base_3_01_behavior_01_4" ],
      [ "domain_base< Destination >", "structossia_1_1net_1_1domain__base_3_01_destination_01_4.html", "structossia_1_1net_1_1domain__base_3_01_destination_01_4" ],
      [ "domain_base< Impulse >", "structossia_1_1net_1_1domain__base_3_01_impulse_01_4.html", "structossia_1_1net_1_1domain__base_3_01_impulse_01_4" ],
      [ "domain_base< String >", "structossia_1_1net_1_1domain__base_3_01_string_01_4.html", "structossia_1_1net_1_1domain__base_3_01_string_01_4" ],
      [ "domain_base< Tuple >", "structossia_1_1net_1_1domain__base_3_01_tuple_01_4.html", "structossia_1_1net_1_1domain__base_3_01_tuple_01_4" ],
      [ "domain_base< Vec< float, N > >", "structossia_1_1net_1_1domain__base_3_01_vec_3_01float_00_01_n_01_4_01_4.html", "structossia_1_1net_1_1domain__base_3_01_vec_3_01float_00_01_n_01_4_01_4" ],
      [ "domain_clamp_visitor", "structossia_1_1net_1_1domain__clamp__visitor.html", "structossia_1_1net_1_1domain__clamp__visitor" ],
      [ "domain_conversion", "structossia_1_1net_1_1domain__conversion.html", "structossia_1_1net_1_1domain__conversion" ],
      [ "domain_conversion< domain_base< Behavior > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_behavior_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_behavior_01_4_01_4" ],
      [ "domain_conversion< domain_base< Destination > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_destination_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_destination_01_4_01_4" ],
      [ "domain_conversion< domain_base< Impulse > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_impulse_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_impulse_01_4_01_4" ],
      [ "domain_conversion< domain_base< String > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_string_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_string_01_4_01_4" ],
      [ "domain_conversion< domain_base< Tuple > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_tuple_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_tuple_01_4_01_4" ],
      [ "domain_conversion< domain_base< Vec< float, N > > >", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_vec_3_01float_00_01_n_01_4_01_4_01_4.html", "structossia_1_1net_1_1domain__conversion_3_01domain__base_3_01_vec_3_01float_00_01_n_01_4_01_4_01_4" ],
      [ "domain_creation_visitor", "structossia_1_1net_1_1domain__creation__visitor.html", "structossia_1_1net_1_1domain__creation__visitor" ],
      [ "domain_max_visitor", "structossia_1_1net_1_1domain__max__visitor.html", "structossia_1_1net_1_1domain__max__visitor" ],
      [ "domain_min_visitor", "structossia_1_1net_1_1domain__min__visitor.html", "structossia_1_1net_1_1domain__min__visitor" ],
      [ "generic_address", "classossia_1_1net_1_1generic__address.html", "classossia_1_1net_1_1generic__address" ],
      [ "generic_device", "classossia_1_1net_1_1generic__device.html", "classossia_1_1net_1_1generic__device" ],
      [ "generic_node", "classossia_1_1net_1_1generic__node.html", "classossia_1_1net_1_1generic__node" ],
      [ "local_protocol", "classossia_1_1net_1_1local__protocol.html", "classossia_1_1net_1_1local__protocol" ],
      [ "minuit_protocol", "classossia_1_1net_1_1minuit__protocol.html", "classossia_1_1net_1_1minuit__protocol" ],
      [ "node_base", "classossia_1_1net_1_1node__base.html", "classossia_1_1net_1_1node__base" ],
      [ "osc_protocol", "classossia_1_1net_1_1osc__protocol.html", "classossia_1_1net_1_1osc__protocol" ],
      [ "OSCInboundVisitor", "structossia_1_1net_1_1_o_s_c_inbound_visitor.html", "structossia_1_1net_1_1_o_s_c_inbound_visitor" ],
      [ "OSCOutboundVisitor", "structossia_1_1net_1_1_o_s_c_outbound_visitor.html", "structossia_1_1net_1_1_o_s_c_outbound_visitor" ],
      [ "protocol_base", "classossia_1_1net_1_1protocol__base.html", "classossia_1_1net_1_1protocol__base" ]
    ] ],
    [ "automation", "classossia_1_1automation.html", "classossia_1_1automation" ],
    [ "Behavior", "structossia_1_1_behavior.html", "structossia_1_1_behavior" ],
    [ "Bool", "structossia_1_1_bool.html", "structossia_1_1_bool" ],
    [ "callback_container", "classossia_1_1callback__container.html", "classossia_1_1callback__container" ],
    [ "Char", "structossia_1_1_char.html", "structossia_1_1_char" ],
    [ "clock", "classossia_1_1clock.html", "classossia_1_1clock" ],
    [ "curve", "classossia_1_1curve.html", "classossia_1_1curve" ],
    [ "curve_abstract", "classossia_1_1curve__abstract.html", "classossia_1_1curve__abstract" ],
    [ "curve_segment_ease", "structossia_1_1curve__segment__ease.html", "structossia_1_1curve__segment__ease" ],
    [ "curve_segment_empty", "structossia_1_1curve__segment__empty.html", "structossia_1_1curve__segment__empty" ],
    [ "curve_segment_linear", "structossia_1_1curve__segment__linear.html", "structossia_1_1curve__segment__linear" ],
    [ "curve_segment_power", "structossia_1_1curve__segment__power.html", "structossia_1_1curve__segment__power" ],
    [ "curve_segment_sin", "structossia_1_1curve__segment__sin.html", "structossia_1_1curve__segment__sin" ],
    [ "custom_state", "classossia_1_1custom__state.html", "classossia_1_1custom__state" ],
    [ "Destination", "classossia_1_1_destination.html", "classossia_1_1_destination" ],
    [ "Float", "structossia_1_1_float.html", "structossia_1_1_float" ],
    [ "Impulse", "structossia_1_1_impulse.html", "structossia_1_1_impulse" ],
    [ "Int", "structossia_1_1_int.html", "structossia_1_1_int" ],
    [ "loop", "classossia_1_1loop.html", "classossia_1_1loop" ],
    [ "mapper", "classossia_1_1mapper.html", "classossia_1_1mapper" ],
    [ "message", "structossia_1_1message.html", "structossia_1_1message" ],
    [ "network_logger", "classossia_1_1network__logger.html", "classossia_1_1network__logger" ],
    [ "scenario", "classossia_1_1scenario.html", "classossia_1_1scenario" ],
    [ "state", "classossia_1_1state.html", "classossia_1_1state" ],
    [ "state_execution_visitor", "structossia_1_1state__execution__visitor.html", "structossia_1_1state__execution__visitor" ],
    [ "state_flatten_visitor", "structossia_1_1state__flatten__visitor.html", "structossia_1_1state__flatten__visitor" ],
    [ "state_print_visitor", "structossia_1_1state__print__visitor.html", "structossia_1_1state__print__visitor" ],
    [ "String", "structossia_1_1_string.html", "structossia_1_1_string" ],
    [ "time_constraint", "classossia_1_1time__constraint.html", "classossia_1_1time__constraint" ],
    [ "time_event", "classossia_1_1time__event.html", "classossia_1_1time__event" ],
    [ "time_node", "classossia_1_1time__node.html", "classossia_1_1time__node" ],
    [ "time_process", "classossia_1_1time__process.html", "classossia_1_1time__process" ],
    [ "time_value", "classossia_1_1time__value.html", "classossia_1_1time__value" ],
    [ "Tuple", "structossia_1_1_tuple.html", "structossia_1_1_tuple" ],
    [ "value", "classossia_1_1value.html", "classossia_1_1value" ],
    [ "value_comparison_visitor", "structossia_1_1value__comparison__visitor.html", "structossia_1_1value__comparison__visitor" ],
    [ "value_trait", "structossia_1_1value__trait.html", null ],
    [ "value_trait< ossia::Bool >", "structossia_1_1value__trait_3_01ossia_1_1_bool_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_bool_01_4" ],
    [ "value_trait< ossia::Char >", "structossia_1_1value__trait_3_01ossia_1_1_char_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_char_01_4" ],
    [ "value_trait< ossia::Destination >", "structossia_1_1value__trait_3_01ossia_1_1_destination_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_destination_01_4" ],
    [ "value_trait< ossia::Float >", "structossia_1_1value__trait_3_01ossia_1_1_float_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_float_01_4" ],
    [ "value_trait< ossia::Impulse >", "structossia_1_1value__trait_3_01ossia_1_1_impulse_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_impulse_01_4" ],
    [ "value_trait< ossia::Int >", "structossia_1_1value__trait_3_01ossia_1_1_int_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_int_01_4" ],
    [ "value_trait< ossia::String >", "structossia_1_1value__trait_3_01ossia_1_1_string_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_string_01_4" ],
    [ "value_trait< ossia::Tuple >", "structossia_1_1value__trait_3_01ossia_1_1_tuple_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_tuple_01_4" ],
    [ "value_trait< ossia::Vec< float, 2 > >", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_012_01_4_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_012_01_4_01_4" ],
    [ "value_trait< ossia::Vec< float, 3 > >", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_013_01_4_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_013_01_4_01_4" ],
    [ "value_trait< ossia::Vec< float, 4 > >", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_014_01_4_01_4.html", "structossia_1_1value__trait_3_01ossia_1_1_vec_3_01float_00_014_01_4_01_4" ],
    [ "Vec", "classossia_1_1_vec.html", "classossia_1_1_vec" ]
];